import { CardsSkeleton } from "@/components/skeletons";
import RenderPost from "@/views/RenderPost";
import Search from "@/components/search";
import { Suspense } from "react";

export default function Home({
  searchParams,
}: {
  searchParams?: {
    query?: string;
    page?: string;
  };
}) {
  const query = searchParams?.query || "";
  const currentPage = Number(searchParams?.page) || 1;

  return (
    <main className="py-2 px-10">
      <section className="max-w-7xl mx-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning
            images generated by DALL-E AI , DALL-E-3 AI
          </p>
        </div>
        <div className="mt-10">
          <Search placeholder="Search something..." />
        </div>
      </section>
      <Suspense key={query + currentPage} fallback={<CardsSkeleton />}>
        <RenderPost query={query} />
      </Suspense>
    </main>
  );
}
